name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            source /home/mhrsifa1/nodevenv/logitrack.mhrsifat.xyz/22/bin/activate
            cd /home/mhrsifa1/logitrack.mhrsifat.xyz
            git pull origin main
            npm install
            npm run build
            rm -rf /home/mhrsifa1/public_html/*
            cp -r dist/* /home/mhrsifa1/public_html/
